export default {
    ROLE_ADMIN: 'ROLE_ADMIN',
    ROLE_DOCTOR: 'ROLE_DOCTOR',
    ROLE_STOCKER: 'ROLE_STOCKER',
    ROLE_GUEST: 'ROLE__GUEST',
    ROLE_PATIENT: 'ROLE_PATIENT',
    ROLE_RECEIPTION: 'ROLE_RECEIPTIO'
}